In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [5]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

In [17]:
# R-squared
reg.score(x, y)

0.4066811952814283

In [18]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [19]:
reg.intercept_

0.29603261264909486

In [22]:
# Adjusted R-squared
r2 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]
adjRSquared = 1 - (1 - r2)*((n-1)/(n-p-1))
adjRSquared

0.3920313482513401

In [23]:
# Feature Selection to remove unsignificant features
from sklearn.feature_selection import f_regression

In [24]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [25]:
p_values = f_regression(x, y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [26]:
p_values.round(3)

array([0.   , 0.676])

In [30]:
# Creating a summary table
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [31]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['Intercepts'] = reg.intercept_
reg_summary ['p-values'] = p_values.round(3)

In [32]:
reg_summary

Features  Coefficients  Intercepts  p-values
0         SAT      0.001654    0.296033     0.000
1  Rand 1,2,3     -0.008270    0.296033     0.676